// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2NaUEA1wX7BNnrq_ZUgwXmRYQVKybIOw',
    appId: '1:1642601678:web:c61b1bf9bfba044570c49f',
    messagingSenderId: '1642601678',
    projectId: 'tubonge-app-70c7d',
    authDomain: 'tubonge-app-70c7d.firebaseapp.com',
    storageBucket: 'tubonge-app-70c7d.appspot.com',
    measurementId: 'G-19VST9VCJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJU6BbXUr3sq_QIL2Ffbh66LsINqRq5nM',
    appId: '1:1642601678:android:a1680313fde7bdec70c49f',
    messagingSenderId: '1642601678',
    projectId: 'tubonge-app-70c7d',
    storageBucket: 'tubonge-app-70c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr0pvkHo-kYPRx5oDo1OYZMtEZDOp3R4U',
    appId: '1:1642601678:ios:1661311fea940e0e70c49f',
    messagingSenderId: '1642601678',
    projectId: 'tubonge-app-70c7d',
    storageBucket: 'tubonge-app-70c7d.appspot.com',
    iosBundleId: 'com.example.tubongeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr0pvkHo-kYPRx5oDo1OYZMtEZDOp3R4U',
    appId: '1:1642601678:ios:1661311fea940e0e70c49f',
    messagingSenderId: '1642601678',
    projectId: 'tubonge-app-70c7d',
    storageBucket: 'tubonge-app-70c7d.appspot.com',
    iosBundleId: 'com.example.tubongeApp',
  );
}
